modLoader="javafml"
license="CC BY-NC-SA 3.0"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/VazkiiMods/Patchouli"
logoFile="logo.png"

[[mods]]
modId="patchouli"
displayName="Patchouli"
version="${file.jarVersion}"
authors="Vazkii"
description='''
Accessible, Data-Driven, Dependency-Free Documentation for Minecraft Modders and Pack Makers
'''

[[dependencies.patchouli]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.0.31-beta,)"

[[dependencies.patchouli]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21,1.22)"

[[mixins]]
config="patchouli_xplat.mixins.json"